name: xDaily
main: de.xearox.xdaily.XDaily
version: 0.0.1
authors: [Xearox]
website: "http://minecraft.xearox.de"
softdepend: [Vault]

commands:
  daily:
    description: TestCommand
    usage: /<command>
  test:
    description: TestCommand
    usage: /<command>  
    
#permissions:
#  home.*:
#    description: Access to all home commands
#    children:
#      home.rl: true
#      home.set.mainhome: true
#      home.set.diffhome: true
#      home.list: true
#      home.del: true
#      home.teleport.mainhome: true
#      home.teleport.diffhome: true
#      home.update: true
#      home.getOPMessage: true
#      home.getPermissionGroups: true
#      home.debugCommands: true
#  home.rl:
#    description: Access to reload yaml files
#    default: op