name: xDaily
main: de.xearox.xdaily.XDaily
version: 0.6.8
authors: [Xearox]
website: "http://minecraft.xearox.de"
softdepend: [Vault]

commands:
  daily:
    description: TestCommand
    usage: /<command>, [admin], [admin] [rewriteplayerfiles], [admin] [addVIP] (PlayerName)
  test:
    description: TestCommand
    usage: /<command>  
    
permissions:
  daily.*:
    description: Access to all daily reset commands
    children:
      daily.admin: true
      daily.admin.rewriteplayerfiles: true
      daily.admin.addVIP: true
      #daily.set.diffhome: true
      #daily.list: true
      #daily.del: true
      #daily.teleport.mainhome: true
      #daily.teleport.diffhome: true
      #daily.update: true
      #daily.getOPMessage: true
      #daily.getPermissionGroups: true
      #daily.debugCommands: true
  daily:
    description: Daily Configuration GUI
    default: true
  daily.admin:
    description: Daily Configuration GUI
    default: op
  daily.admin.rewriteplayerfiles:
    description: If you change the reward days you need to rewrite the player files
    default: op
  daily.admin.addVIP:
    description: Add the player's UUID to the VIP file
    default: op