name: xHome
main: de.xearox.xplugin.MainClass
version: 0.6.0
author: Xearox

commands:
  home:
    description: MyHomes to set homes or multiple homes
    usage: /<command> ,[set], [set] [homename], [del] [homename], [list]