name: xConomy
main: de.xearox.xconomy.XConomy
version: 0.0.1
authors: [Xearox]
website: "http://minecraft.xearox.de"
loadbefore: [xHome]
commands:
  money:
    description: money function
    usage: /<command> ,[send] [TargetPlayer] [Amount], [add] [TargetPlayer] [Amount]
  ecweb:
    description: Webinterface
    usage: /<command> register Username Password