name: xEnchants
main: de.xearox.xenchants.XEnchants
version: 0.0.1
authors: [Xearox]
website: "http://minecraft.xearox.de"

commands:
  enchantment:
    description: Opens the Enchantment Inventory
    usage: /<command>