name: xFriends
main: de.xearox.xfriends.XFriends
version: 0.0.1
authors: [Xearox]
website: "http://minecraft.xearox.de"

commands:
  friends:
    description: Main function for the xFriends plugin
    usage: /<command>, [admin], [register] (Password) (Email)
#  test:
#    description: TestCommand
#    usage: /<command>